### ISSUE TITLE
请教一个配置nginx 配置问题

### ISSUE THREAD

**Issue by liuing-org** [xuexb/learn-nginx#21]
目前主机在内网环境没有域名,主机上使用端口运行服务,一个javaweb网站,
由于使用多个服务,希望能将端口反代成二级目录
使用proxy_pass 代理后出现web服务的静态资源无法访问,查看浏览器发现静态资源端口号没有反代
nginx 配置如下
  location /wx/ {
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Prefix /wx;
            proxy_pass http://127.0.0.1:8080;
        }
望解答!

**Comment by xuexb** [comment]
对于你的 8080 javaweb 来说，代理过去应该是 `http://127.0.0.1:8080/wv/` 。你的静态资源也需要基于这样的二有目录才行。

比如：你本来是 `http://127.0.0.1:8080/a.js` ，想使用 `http://www.xxx.com/wx/a.js` 访问。其实改一行代码就行：

```diff
- proxy_pass http://127.0.0.1:8080;
+ proxy_pass http://127.0.0.1:8080/;
```

`proxy_pass` 命令有路径结尾时，会把 `location /wx/ {}` 匹配到的内容往后追加，如：

- `http://www.xuexb.com/wv/` -> `http://127.0.0.1:8080/`
- `http://www.xuexb.com/wv/a.js` -> `http://127.0.0.1:8080/a.js`
- `http://www.xuexb.com/wv/a/b/c.js` -> `http://127.0.0.1:8080/a/b/c.js`

但其实这样不好，因为前端被访问的代码跟浏览器直接运行的链接不一样。可能会导致加载 404 。我更建议你的 javaweb 也使用二级目录，这样开发时、部署后都是一样的路径。

否则你可以使用二级域名，如：`http://javaweb.xxx.com` ，这种没有二级目录的你更方便。

**Comment by xuexb** [comment]
> 浏览器直接运行的链接不一样

比如前端打包时需要有个 `baseURL` 的概念，如果写 `/` 吧，在你代理域名环境就会404；所以打包时应该也要基于 `/wx/` 打二级目录才行。
