### ISSUE TITLE
Wish this is getting an English translation anytime soon

### ISSUE THREAD

**Issue by 0xMH** [xuexb/learn-nginx#3]

**Comment by xuexb** [comment]
hi, 我不太会英语，不过这两天我打算创建一个站点 #4 ，到时候欢迎一起翻译~

---
Hey, I don't know English very much, but these two days I plan to create a site #4, and welcome to translate together~

**Comment by MoHD20** [comment]
Hey, I'd be really happy to help but unfortunately I don't know Chinese :( If you got any idea on how we could collaborate, I am all ears.
